lidar_odometry_node:
 ros__parameters:
  init_scans: 20
  voxel_leaf: 0.03
  correspondence: 1.0
  epsilon: 1.0e-6
  local_submap_distance: 4.0
  EnableCropDistance: true
  fitness_score: 0.3
  max_noiseDistance: 0.005
  icp_iterations: 25
  max_scan_queue: 45
  scan_trim_size: 30
  odometry_frame_id: odom
  odom_topic: /odom
  robot_frame_id: base_link
  watchdog_timeout: 60
  keyframe_translation_thresh: 0.5
  keyframe_rotation_thresh: 0.3
  keyframe_min_translation_for_rotation: 0.1
  keyframe_last_frame_time: 2.0
  keyframe_pose_topic: /lidar/keyframes/pose
  keyframe_point_topic: /lidar/keyframes/cloud
  aligned_scan_topic: /aligned_scan
  path_topic: /path
  max_imu_queue: 540
  max_submaps: 8
  submap_max_points: 400000
  submap_radius: 4.0
  max_selected_submaps: 3
  submap_dist_thresh: 0.5
  submap_yaw_thresh:  0.174532925
  max_predict_dist: 1.5
  max_rotation_step: 0.785398163
  numFramesStationary: 2
  gyro_threshold: 0.03
  accel_std_threshold: 0.30
  min_imu_samples: 20


